defmodule Mix.Tasks.Encryptor.Ecto.Gen.SuspensionStoreMigration do
  @shortdoc "Writes the suspension table's migration into the host's tree"

  @moduledoc """
  Generates the Ecto migration that creates `Encryptor.Ecto.SuspensionStore`'s
  table.

      mix encryptor.ecto.gen.suspension_store_migration [--table NAME] [--migrations-path PATH]

  The table holds one row per suspended scope per vault: the vault's name, the
  selector, and when the suspension was written (ADR-0007 decision 1).

  ## This task issues no DDL

  It writes one file. Nothing here opens a database connection, and nothing in
  this package issues `CREATE TABLE` at runtime or from a task (ADR-0002
  decision 9). The generated file is yours the moment it lands: review it in a
  diff, commit it, and run it with your own `mix ecto.migrate`.

  The module name is generated from this project's application name and will
  need renaming if your repo lives in another namespace.

  There is no `--prefix`, for the reason
  `mix encryptor.ecto.gen.key_store_migration` gives: run the file with
  `mix ecto.migrate --prefix my_schema` and pass the same name as `prefix:` in
  the store's options.

  ## Flags

  | Flag | | |
  |---|---|---|
  | `--table NAME` | `encryptor_suspensions` | The table to create. A host that renames it passes the same name as `table:` in the store's options |
  | `--migrations-path PATH` | `priv/repo/migrations` | Where to write the file |

  ## Exit codes

  | | |
  |---|---|
  | `0` | The file was written; its path is printed |
  | `2` | Usage error, or a migration for this table already exists in that directory - the generator never overwrites one and never writes a second |

  ## The shape it writes

  One unique index over `{vault, selector}`. It is what makes a repeated
  `Encryptor.Vault.suspend/2` one row rather than two, and what keeps two
  vaults' sets apart in one table.
  """

  use Mix.Task

  alias Encryptor.Ecto.Migrator.CLI
  alias Encryptor.Ecto.SuspensionStore

  @verb "create_"

  @impl Mix.Task
  def run(argv) do
    argv |> main() |> CLI.halt()
  end

  @doc false
  @spec main([String.t()]) :: 0 | 2
  def main(argv) do
    CLI.gen(argv,
      verb: @verb,
      default_table: &SuspensionStore.default_table/0,
      positional_tail: "",
      already_written: :create,
      source: &__MODULE__.source/2,
      migration_module: &__MODULE__.migration_module/1
    )
  end

  @doc false
  @spec source(String.t(), module()) :: String.t()
  def source(table, module) do
    """
    defmodule #{inspect(module)} do
      # The table `Encryptor.Ecto.SuspensionStore` agrees a vault's suspended
      # set in, generated by `mix encryptor.ecto.gen.suspension_store_migration`.
      #
      # `encryptor_ecto` issues no DDL of its own (ADR-0002 decision 9): this
      # file is the host's now. Review it, commit it, and run it with your own
      # `mix ecto.migrate`. Rename the module above if your repo lives in
      # another namespace, and if you rename the table, pass the same name as
      # `table:` in the store's options.
      #
      # `vault` is the vault module's name and `selector` the suspended scope,
      # as the host passed it to `Encryptor.Vault.suspend/2`. The unique index
      # on `{vault, selector}` makes a repeated suspension one row, and keeps
      # two vaults' sets apart in one table.
      @moduledoc false

      use Ecto.Migration

      def change do
        create table(:#{table}) do
          add(:vault, :string, null: false)
          add(:selector, :string, null: false)
          add(:inserted_at, :utc_datetime, null: false)
        end

        create(unique_index(:#{table}, [:vault, :selector]))
      end
    end
    """
  end

  @doc false
  @spec migration_module(String.t()) :: module()
  def migration_module(table), do: CLI.migration_module(@verb, table)
end
