defmodule Mix.Tasks.Encryptor.Ecto.Gen.KeyStoreMigration do
  @shortdoc "Writes the wrapped-key table's migration into the host's tree"

  @moduledoc """
  Generates the Ecto migration that creates `Encryptor.Ecto.KeyStore`'s table.

      mix encryptor.ecto.gen.key_store_migration [--table NAME] [--migrations-path PATH]

  The table holds one row per tenant per key version: the six fields
  `Encryptor.Envelope.WrappedKey` fixes, which is the whole of the vault's
  storage contract (`encryptor` ADR-0003 decision 9), plus the two this
  package's ADR-0005 adds - `wrapping_shape` and `key_id`. The vault owns the
  six; this package owns the table, the two, the migration and the repo.

  ## This task creates tables and never alters one

  It is the whole-table generator, and it refuses to run where a migration for
  the table already exists. An adopter whose table was created under 0.3.0 -
  before `wrapping_shape` and `key_id` existed - wants
  `mix encryptor.ecto.gen.key_store_shape_migration` instead, which writes the
  additive `ALTER` those two columns need.

  ## This task issues no DDL

  It writes one file. Nothing here opens a database connection, and nothing in
  this package issues `CREATE TABLE` at runtime or from a task (ADR-0002
  decision 9) - `Encryptor.Ecto.KeyStore` reads the table and lets the
  adapter's "relation does not exist" raise where creating it would have been
  convenient.
  The generated file is yours the moment it lands: review it in a diff, commit
  it, and run it with your own `mix ecto.migrate`, on your own deploy schedule
  and with your own rollback.

  The module name is generated from this project's application name and will
  need renaming if your repo lives in another namespace.

  ## There is no `--prefix`, on purpose

  A host whose wrapped-key table belongs in a non-default Postgres schema runs
  the generated file with `mix ecto.migrate --prefix my_schema`, which is
  Ecto's own way to place a migration and applies to the table and both
  indexes together, and passes the same name as `prefix:` in its
  `Encryptor.Ecto.KeyStore` provider options. A flag here would write that
  schema name into a file the host commits, which freezes a deployment-time
  placement decision into source that outlives it - the same argument
  `Encryptor.Ecto.Migrator` makes for keeping `:prefix` a run option rather
  than a fact about the plan.

  ## Flags

  | Flag | | |
  |---|---|---|
  | `--table NAME` | `encryptor_wrapped_keys` | The table to create. A host that renames it passes the same name as `table:` in its `Encryptor.Ecto.KeyStore` provider options |
  | `--migrations-path PATH` | `priv/repo/migrations` | Where to write the file |

  ## Exit codes

  | | |
  |---|---|
  | `0` | The file was written; its path is printed |
  | `2` | Usage error, or a migration for this table already exists in that directory - the generator never overwrites one and never writes a second |

  ## The shape it writes

  One row per `{tenant_ref, version}`, with two unique indexes.

  `{tenant_ref, version}` closes the race `encryptor` ADR-0003 leaves to this
  package: `Encryptor.Envelope.provision/3` called twice concurrently for one
  tenant can produce two rows claiming the same version, and a candidate list
  with two entries for one version is a key nobody can vouch for.

  `{namespace, name}` is the name contract made mechanical. `RawAes.unwrap_key/3`
  accepts an encrypted data key only when the header's provider id and key name
  equal the keyring's, so reusing a name for different material makes
  previously written messages undecryptable, silently, at some later date. The
  database is the only thing that can catch it at write time.

  `wrapped` is `:binary` and nothing else: it is a complete `Encryptor` message
  produced by the root vault, so its size is the engine's business and not a
  length this migration should guess at.
  """

  use Mix.Task

  alias Encryptor.Ecto.KeyStore
  alias Encryptor.Ecto.Migrator.CLI

  @default_path "priv/repo/migrations"
  @switches [table: :string, migrations_path: :string]

  @impl Mix.Task
  def run(argv) do
    argv |> main() |> CLI.halt()
  end

  @doc false
  @spec main([String.t()]) :: 0 | 2
  def main(argv) do
    with {:ok, table, path} <- parse(argv),
         :ok <- unwritten(table, path) do
      generate(table, path)
    else
      {:error, message} -> CLI.usage_error(message)
    end
  end

  @doc false
  @spec source(String.t(), module()) :: String.t()
  def source(table, module) do
    """
    defmodule #{inspect(module)} do
      # The wrapped-key table `Encryptor.Ecto.KeyStore` resolves selectors
      # against, generated by `mix encryptor.ecto.gen.key_store_migration`.
      #
      # `encryptor_ecto` issues no DDL of its own (ADR-0002 decision 9): this
      # file is the host's now. Review it, commit it, and run it with your own
      # `mix ecto.migrate`. Rename the module above if your repo lives in
      # another namespace, and if you rename the table, pass the same name as
      # `table:` in the provider's options.
      #
      # The columns are the six fields of `Encryptor.Envelope.WrappedKey` - the
      # whole of the vault's storage contract - plus ADR-0005's two and
      # timestamps. `wrapped` is the wrapping, `:binary` with no length because
      # its size is the engine's business, and `wrapping_shape` says which kind
      # of wrapping it is: `"engine_message"` or `"gcp_kms_ciphertext"`. It has
      # no default on purpose - this package writes no rows, so a forgotten
      # shape should fail at your insert rather than read back later as
      # somebody else's unwrap failure. `key_id` is `NULL` for an engine
      # message and required for a GCP ciphertext.
      #
      # The unique index on `{tenant_ref, version}` closes the race
      # `Encryptor.Envelope.provision/3` leaves open: called twice concurrently
      # for one tenant it can produce two rows claiming one version, and a
      # candidate list with two entries for one version is a key nobody can
      # vouch for. The unique index on `{namespace, name}` is the name contract
      # made mechanical - a name is bound to its bytes forever, and two rows
      # sharing one is the failure that contract exists to prevent.
      @moduledoc false

      use Ecto.Migration

      def change do
        create table(:#{table}) do
          add(:tenant_ref, :string, null: false)
          add(:version, :integer, null: false)
          add(:namespace, :string, null: false)
          add(:name, :string, null: false)
          add(:bits, :integer, null: false)
          add(:wrapped, :binary, null: false)
          add(:wrapping_shape, :string, null: false)
          add(:key_id, :string)
          add(:inserted_at, :utc_datetime)
          add(:updated_at, :utc_datetime)
        end

        create(unique_index(:#{table}, [:tenant_ref, :version]))
        create(unique_index(:#{table}, [:namespace, :name]))
      end
    end
    """
  end

  @doc false
  @spec migration_module(String.t()) :: module()
  def migration_module(table) do
    app =
      Mix.Project.config()
      |> Keyword.fetch!(:app)
      |> Atom.to_string()
      |> Macro.camelize()

    Module.concat([app, "Repo", "Migrations", Macro.camelize("create_" <> table)])
  end

  @spec parse([String.t()]) :: {:ok, String.t(), String.t()} | {:error, String.t()}
  defp parse(argv) do
    case OptionParser.parse(argv, strict: @switches) do
      {parsed, [], []} -> table(parsed)
      {_parsed, [_ | _] = args, []} -> {:error, positional_message(args)}
      {_parsed, _args, invalid} -> {:error, invalid_message(invalid)}
    end
  end

  @spec table(keyword()) :: {:ok, String.t(), String.t()} | {:error, String.t()}
  defp table(parsed) do
    table = Keyword.get(parsed, :table, KeyStore.default_table())
    path = Keyword.get(parsed, :migrations_path, @default_path)

    if table =~ ~r/^[a-z_][a-z0-9_]*$/ do
      {:ok, table, path}
    else
      {:error,
       "--table expects an unquoted table name - lowercase letters, digits and " <>
         "underscores - and cannot use #{inspect(table)}"}
    end
  end

  @spec positional_message([String.t()]) :: String.t()
  defp positional_message(args) do
    "takes no positional arguments and was given #{Enum.join(args, " ")}. This verb " <>
      "writes a file and reads no plan."
  end

  @spec invalid_message([{String.t(), term()}]) :: String.t()
  defp invalid_message(invalid) do
    Enum.map_join(invalid, "\n", fn {flag, _value} ->
      "#{flag} is not a flag of this task, or was given a value of the wrong type."
    end)
  end

  @spec unwritten(String.t(), String.t()) :: :ok | {:error, String.t()}
  defp unwritten(table, path) do
    case Path.wildcard(Path.join(path, "*_create_#{table}.exs")) do
      [] -> :ok
      [existing | _rest] -> {:error, already_written_message(existing)}
    end
  end

  @spec already_written_message(String.t()) :: String.t()
  defp already_written_message(existing) do
    "#{existing} already creates this table. The generator never overwrites a " <>
      "migration and never writes a second one for the same table: a repeated " <>
      "`CREATE TABLE` fails on the way up, and the one you have is the one your " <>
      "database was built from."
  end

  @spec generate(String.t(), String.t()) :: 0
  defp generate(table, path) do
    file = Path.join(path, "#{timestamp()}_create_#{table}.exs")

    File.mkdir_p!(path)
    File.write!(file, source(table, migration_module(table)))
    Mix.shell().info("* creating #{file}")

    0
  end

  @spec timestamp() :: String.t()
  defp timestamp do
    now = DateTime.utc_now()

    [now.year, now.month, now.day, now.hour, now.minute, now.second]
    |> Enum.map_join(&pad/1)
  end

  @spec pad(integer()) :: String.t()
  defp pad(number) when number < 10, do: "0#{number}"
  defp pad(number), do: Integer.to_string(number)
end
