defmodule Mix.Tasks.Encryptor.Ecto.Gen.Migration do
  @shortdoc "Writes the checkpoint table's migration into the host's tree"

  @moduledoc """
  Generates the Ecto migration that creates the migrator's checkpoint table.

      mix encryptor.ecto.gen.migration [--table NAME] [--migrations-path PATH]

  The pass records `{plan, schema, field, prefix, last_id, counts}` after each
  batch, inside the batch's own transaction, and `--resume` starts after the
  recorded cursor (ADR-0002 decision 6). The table that lives in is the
  **host's**, and this package will not create it.

  ## This task issues no DDL

  It writes one file. Nothing here opens a database connection, and nothing in
  this package issues `CREATE TABLE` at runtime or from a task (ADR-0002
  decision 9): `Encryptor.Ecto.Migrator.run/2` preflights the table and
  *refuses*, naming this generator, where creating it would have been
  convenient. Authoring the DDL and holding authority over the host's schema
  are different things, and only the second is refused - so the generated file
  is yours the moment it lands: review it in a diff, commit it, and run it
  with your own `mix ecto.migrate`, on your own deploy schedule and with your
  own rollback.

  Two consequences worth stating, because a generator that looked like an
  installer would hide both. The module name is generated from this project's
  application name and will need renaming if your repo lives in another
  namespace. And a host that will not add the table at all is not stuck: it
  runs `mix encryptor.ecto.migrate --no-checkpoint`, where every run is a full
  scan, which probe-first idempotence makes correct rather than merely
  tolerable.

  ## Flags

  | Flag | | |
  |---|---|---|
  | `--table NAME` | `encryptor_ecto_migration_checkpoints` | The table to create. A host that renames it passes the same name as `checkpoint_table:` to `Encryptor.Ecto.Migrator.run/2` |
  | `--migrations-path PATH` | `priv/repo/migrations` | Where to write the file |

  ## Exit codes

  | | |
  |---|---|
  | `0` | The file was written; its path is printed |
  | `2` | Usage error, or a migration for this table already exists in that directory - the generator never overwrites one and never writes a second |

  ## The shape it writes

  One row per field per prefix, with a unique index over
  `{plan, schema, field, prefix}`. `prefix` is `NOT NULL` with an empty-string
  default rather than nullable, because a `NULL` component defeats the unique
  index in every adapter that treats `NULL`s as distinct - which would let two
  rows exist for the default prefix and make the upsert stop finding the row
  it wrote last time. `last_id` is text because both integer and binary
  primary keys are supported and one checkpoint table serves both.
  """

  use Mix.Task

  alias Encryptor.Ecto.Migrator.Checkpoint
  alias Encryptor.Ecto.Migrator.CLI

  @default_path "priv/repo/migrations"
  @switches [table: :string, migrations_path: :string]

  @impl Mix.Task
  def run(argv) do
    argv |> main() |> CLI.halt()
  end

  @doc false
  @spec main([String.t()]) :: 0 | 2
  def main(argv) do
    with {:ok, table, path} <- parse(argv),
         :ok <- unwritten(table, path) do
      generate(table, path)
    else
      {:error, message} -> CLI.usage_error(message)
    end
  end

  @doc false
  @spec source(String.t(), module()) :: String.t()
  def source(table, module) do
    """
    defmodule #{inspect(module)} do
      # The checkpoint table `Encryptor.Ecto.Migrator` records its cursor in,
      # generated by `mix encryptor.ecto.gen.migration`.
      #
      # `encryptor_ecto` issues no DDL of its own (ADR-0002 decision 9): this
      # file is the host's now. Review it, commit it, and run it with your own
      # `mix ecto.migrate`. Rename the module above if your repo lives in
      # another namespace, and if you rename the table, pass the same name as
      # `checkpoint_table:` to `Encryptor.Ecto.Migrator.run/2`.
      #
      # `prefix` is NOT NULL with an empty-string default rather than nullable:
      # a NULL component defeats the unique index in every adapter that treats
      # NULLs as distinct, which would let two rows exist for the repo's default
      # prefix and make the checkpoint upsert stop finding the row it wrote last
      # time. `last_id` is text because both integer and binary primary keys are
      # supported and one checkpoint table serves both.
      @moduledoc false

      use Ecto.Migration

      def change do
        create table(:#{table}) do
          add(:plan, :string, null: false)
          add(:schema, :string, null: false)
          add(:field, :string, null: false)
          add(:prefix, :string, null: false, default: "")
          add(:last_id, :string, null: false)
          add(:counts, :map)
          add(:started_at, :utc_datetime)
          add(:updated_at, :utc_datetime)
        end

        create(unique_index(:#{table}, [:plan, :schema, :field, :prefix]))
      end
    end
    """
  end

  @doc false
  @spec migration_module(String.t()) :: module()
  def migration_module(table) do
    app =
      Mix.Project.config()
      |> Keyword.fetch!(:app)
      |> Atom.to_string()
      |> Macro.camelize()

    Module.concat([app, "Repo", "Migrations", Macro.camelize("create_" <> table)])
  end

  @spec parse([String.t()]) :: {:ok, String.t(), String.t()} | {:error, String.t()}
  defp parse(argv) do
    case OptionParser.parse(argv, strict: @switches) do
      {parsed, [], []} -> table(parsed)
      {_parsed, [_ | _] = args, []} -> {:error, positional_message(args)}
      {_parsed, _args, invalid} -> {:error, invalid_message(invalid)}
    end
  end

  @spec table(keyword()) :: {:ok, String.t(), String.t()} | {:error, String.t()}
  defp table(parsed) do
    table = Keyword.get(parsed, :table, Checkpoint.default_table())
    path = Keyword.get(parsed, :migrations_path, @default_path)

    if table =~ ~r/^[a-z_][a-z0-9_]*$/ do
      {:ok, table, path}
    else
      {:error,
       "--table expects an unquoted table name - lowercase letters, digits and " <>
         "underscores - and cannot use #{inspect(table)}"}
    end
  end

  @spec positional_message([String.t()]) :: String.t()
  defp positional_message(args) do
    "takes no positional arguments and was given #{Enum.join(args, " ")}. This verb " <>
      "writes a file and reads no plan; the plan-taking verbs are " <>
      "`mix encryptor.ecto.migrate` and `mix encryptor.ecto.verify`."
  end

  @spec invalid_message([{String.t(), term()}]) :: String.t()
  defp invalid_message(invalid) do
    Enum.map_join(invalid, "\n", fn {flag, _value} ->
      "#{flag} is not a flag of this task, or was given a value of the wrong type."
    end)
  end

  @spec unwritten(String.t(), String.t()) :: :ok | {:error, String.t()}
  defp unwritten(table, path) do
    case Path.wildcard(Path.join(path, "*_create_#{table}.exs")) do
      [] -> :ok
      [existing | _rest] -> {:error, already_written_message(existing)}
    end
  end

  @spec already_written_message(String.t()) :: String.t()
  defp already_written_message(existing) do
    "#{existing} already creates this table. The generator never overwrites a " <>
      "migration and never writes a second one for the same table: a repeated " <>
      "`CREATE TABLE` fails on the way up, and the one you have is the one your " <>
      "database was built from."
  end

  @spec generate(String.t(), String.t()) :: 0
  defp generate(table, path) do
    file = Path.join(path, "#{timestamp()}_create_#{table}.exs")

    File.mkdir_p!(path)
    File.write!(file, source(table, migration_module(table)))
    Mix.shell().info("* creating #{file}")

    0
  end

  @spec timestamp() :: String.t()
  defp timestamp do
    now = DateTime.utc_now()

    [now.year, now.month, now.day, now.hour, now.minute, now.second]
    |> Enum.map_join(&pad/1)
  end

  @spec pad(integer()) :: String.t()
  defp pad(number) when number < 10, do: "0#{number}"
  defp pad(number), do: Integer.to_string(number)
end
